apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  name: deployment-guestbook-frontend
  namespace: guestbook
  generation: 1
  labels:
    application: guestbook
    version: 1.0.0
spec:
  hybridtemplates:
    - deployerType: kubernetes
      template:
        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          name: frontend
          namespace: guestbook
          labels:
            app: guestbook
        spec:
          progressDeadlineSeconds: 600
          replicas: 3
          revisionHistoryLimit: 10
          selector:
            matchLabels:
              app: guestbook
              tier: frontend
          strategy:
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 25%
            type: RollingUpdate
          template:
            metadata:
              labels:
                app: guestbook
                tier: frontend
            spec:
              containers:
                - name: php-redis
                  env:
                    - name: GET_HOSTS_FROM
                      value: dns
                  image: 'gcr.io/google-samples/gb-frontend:v4'
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 80
                      protocol: TCP
                  resources:
                    requests:
                      cpu: 100m
                      memory: 100Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
              dnsPolicy: ClusterFirst
              restartPolicy: Always
              schedulerName: default-scheduler
              securityContext: {}
              terminationGracePeriodSeconds: 30
  placement:
    deployers:
      - namespace: guestbook
