apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3000
  selector:
    app: guestbook
    tier: frontend
