{{- if .Values.redis.slaveEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: {{ .Values.redis.port }}
  selector:
    app: redis
    role: slave
    tier: backend
{{- end }}
