apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: guestbook
    role: redis-master
    tier: backend
spec:
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app: guestbook
    role: redis-master
    tier: backend