apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      role: redis-master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        role: redis-master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: {{ .Values.redis.port }}
