{{- if .Values.redis.slaveEnabled -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      role: redis-slave
      tier: backend
  replicas: {{ .Values.replicaCountRedisSlave }}
  template:
    metadata:
      labels:
        app: guestbook
        role: redis-slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: {{ .Values.redis.port }}
{{- end }}