apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  name: service-guestbook-frontend
  namespace: guestbook
  generation: 1
  labels:
    application: guestbook
    version: 1.0.0
spec:
  hybridtemplates:
    - deployerType: kubernetes
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: frontend
          namespace: guestbook
          finalizers:
            - service.kubernetes.io/load-balancer-cleanup
          labels:
            app: guestbook
            tier: frontend
        spec:
          clusterIP: 172.21.63.119
          externalTrafficPolicy: Cluster
          ports:
            - nodePort: 30429
              port: 80
              protocol: TCP
              targetPort: 80
          selector:
            app: guestbook
            tier: frontend
          sessionAffinity: None
          type: LoadBalancer
  placement:
    deployers:
      - namespace: guestbook