apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: guestbook-deploy
  namespace: guestbook
  labels:
    app: guestbook-1.0.0
spec:
  type: HelmRepo
  pathname: https://davidmccarty.github.io/guestbook-helm/guestbook-1.0.0.tgz
