apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  name: service-guestbook-redis-slave
  namespace: guestbook
  generation: 1
  labels:
    application: guestbook
    version: 1.0.0
spec:
  hybridtemplates:
    - deployerType: kubernetes
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: redis-slave
          namespace: guestbook
          labels:
            app: redis
            role: slave
            tier: backend
        spec:
          clusterIP: 172.21.67.187
          ports:
            - port: 6379
              protocol: TCP
              targetPort: 6379
          selector:
            app: redis
            role: slave
            tier: backend
          sessionAffinity: None
          type: ClusterIP
  placement:
    deployers:
      - namespace: guestbook