placement:
  placementRef:
    name: 
    kind: PlacementRule

apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: guestbook-placement-rule
  namespace: guestbook
  labels:
    app: guestbook
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: OK
  clusterLabels:
    matchLabels:
      env: guestbook-dev